### ISSUE TITLE
Short bios für Team page

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#49]
Für die Team-Page benötige ich short bios von Andreas und Susanne in der Länge von rund 100 Wörtern in de & en.

**Comment by simgan** [comment]
Andreas Krimbacher entwickelt die Software für _Campus Medius_ 2.0. Er verwendet ausschließlich Open-Source-Technologien und stellt den Projektcode auf [GitHub](https://github.com/campusmedius/campusmedius/) unter der MIT-Lizenz zur Verfügung. Das Backend der Website ist in Django und PostgreSQL programmiert, das Frontend in Angular und Mapbox GL JS. Er studierte Geomatic Engineering an der Universität Graz (BA 2012) und der ETH Zürich (MSc 2014). Seit 2015 arbeitet er bei der österreichischen Zentralanstalt für Meteorologie und Geodynamik (ZAMG) als Software-Entwickler und Systemarchitekt.

Andreas Krimbacher has developed the software for _Campus Medius_ 2.0. He employs only open-source technologies and makes the project code available under the MIT license at [GitHub](https://github.com/campusmedius/campusmedius/). The website's back end is programmed in Django und PostgreSQL, the front end in Angular and Mapbox GL JS. He studied Geomatics Engineering at the University of Graz (BA 2012) and the ETH Zurich (MSc 2014). Since 2015, he has been working at the Austrian Zentralanstalt für Meteorologie und Geodynamik (ZAMG) as a software developer and system architect.

**Comment by simgan** [comment]
Susanne Kiesenhofer [Link?] designt die Website von _Campus Medius_ 2.0. Sie studierte digitale Medientechnik an der Fachhochschule St. Pölten (BA 2012) sowie Mediendesign an der Fachhochschule Vorarlberg (MA 2016). Seit 2017 arbeitet sie im Innovation Lab der Kommunikationsagentur Milla & Partner. Daneben ist sie als Hochschullehrerin für interaktive Medien sowie als selbständige Mediendesignerin tätig.

Susanne Kiesenhofer has designed the website of Campus Medius 2.0. She studied digital media technology at St. Pölten University of Applied Sciences (BA 2012) and media design at Vorarlberg University of Applied Sciences (BA 2016). Since 2017, she has been working in the innovation lab of the communication agency Milla & Partner. She also teaches interactive media at university level and independently conducts design projects.

**Comment by iamsusey** [comment]
Susanne Kiesenhofer [https://www.susey.at/de/] designt die Website von Campus Medius 2.0. Sie studierte Medientechnik an der Fachhochschule St. Pölten (BSc 2012) sowie InterMedia an der Fachhochschule Vorarlberg (MA 2016). Seit 2017 arbeitet sie im Innovationslabor von Milla & Partner, einer Agentur für Kommunikation im Raum. 

Susanne Kiesenhofer [https://www.susey.at/en/] has designed the website of Campus Medius 2.0. She studied media technology at St. Pölten University of Applied Sciences (BSc 2012) and InterMedia at Vorarlberg University of Applied Sciences (MA 2016). Since 2017, she has been working in the innovation lab of Milla & Partner, an agency for spatial communication.
